#+title: R 语言中的线性代数
#+author: zbliang
#+DATE: 2026-09-08
#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: posts
#+HUGO_PAIRED_OUT_DIR: ../static
#+HUGO_TAGS: R "Linear Algebra"
#+HUGO_CATEGORIES: tech
#+HUGO_DRAFT: false

#+STARTUP: show2levels
#+PROPERTY: header-args:R :session *R* :eval no-export :results output :exports both

#+BEGIN_EXPORT html
<style>
  /* 仅在这篇文章中生效的临时样式 */
  .question {
      border: 2px solid #666;
      background-color: #f5f5f5;
      padding: 1em;
      margin: 1em 0;
      border-radius: 8px;
  }
  .solution {
      border-left: 5px solid green;
      padding-left: 1em;
      margin: 1em 0;
  }
</style>
#+END_EXPORT

参考资料
+ [[https://css18.github.io/linear-algebra.html][Linear algebra in R]]
+ Ruriko Yoshida. /Linear Algebra and Its Applications with R/, CRC Press, 2021.

本笔记需要用到以下的 =R= 宏包：

#+begin_src R
  library(MASS) # R 内置包，无需安装
  library(matlib) # 不是内置包，需安装
#+end_src

#+RESULTS[84322cdd65472f65dcc6241e9fa1f7348bec00cc]:

* 矩阵
** 创建矩阵

利用 =matrix= 可以创建矩阵。
例如

#+begin_src R
  A <- matrix(c(1, 2, 3, 4, 5, -6, -7, -8, -9, -10, 11, 12, 13, 14, 15), 5, 3)
  A
#+end_src

#+RESULTS[9725140a89614f4baaaab1ae48e6495034ed16ae]:
: [,1] [,2] [,3]
: [1,]    1   -6   11
: [2,]    2   -7   12
: [3,]    3   -8   13
: [4,]    4   -9   14
: [5,]    5  -10   15

就创建了$5\times 3$ 矩阵
$A=\left[\begin{array}{cc}
1 & -6 & 11\\
2 & -7 & 12\\
3 & -8 & 13\\
4 & -9 & 14\\
5 & -10 & 15
\end{array}\right]$。

#+begin_src R
  class(A)
  dim(A)
#+end_src

#+RESULTS[eac4977409059efcfd42420858ad68153d774f1b]:
: [1] "matrix" "array"
: [1] 5 3

 其中
 + =class(A)= 显示 $A$ 的类型是 =matrix= （具体类型）和 =array= （父类型）。
+ =dim(A)= 的结果显示 $A$ 的阶是 3 行 2 列。

要注意的是，矩阵元素默认是逐列输入。
如果想逐行输入，那么需要加参数 =byrow = TRUE= ，比如

#+begin_src R
  matrix(c(1, -6, 11, 2, -7, 12, 3, -8, 13, 4, -9, 14, 5, -10, 15), 5, 3, byrow = TRUE)
#+end_src

#+RESULTS[c33baa43d7e8eb9723fcc2c16ebb25dce2eb8f70]:
:      [,1] [,2] [,3]
: [1,]    1   -6   11
: [2,]    2   -7   12
: [3,]    3   -8   13
: [4,]    4   -9   14
: [5,]    5  -10   15

利用方括号可以实现引用矩阵 $A$ 各部分。

=A[1,2]= 表示 1 行 2 列的元素：

#+begin_src R
  A[1,2]
  class(A[1,2])
#+end_src

#+RESULTS[3e4c394c5e92f895f8605c90a18cfdd3bcadfc1a]:
: [1] -6
: [1] "numeric"

=A[3,]= 表示第 3 行：

#+begin_src R
  A[3,]
  class(A[3,])
#+end_src

#+RESULTS[15f49be4ba8acd88ac3c293f6f4d57350ef284b8]:
: [1]  3 -8 13
: [1] "numeric"

=A[,2]= 表示第 2 列：

#+begin_src R
  A[,2]
  class(A[,2])
#+end_src

#+RESULTS[ad5bcf953b2683a33f039a8a5fa724a5c279ef36]:
: [1]  -6  -7  -8  -9 -10
: [1] "numeric"

=A[3:5, 1:2]= 表示 3-5 行 1-2 列的子块：

#+begin_src R
  A[3:5,1:2]
  class(A[3:5,1:2])
#+end_src

#+RESULTS[0862a0c673c1835d19c15d9c7fdb6e738a550e5a]:
:      [,1] [,2]
: [1,]    3   -8
: [2,]    4   -9
: [3,]    5  -10
: [1] "matrix" "array"

线性代数中的向量其实是矩阵，向量的创建有两者方法：
+ 把数字列表 =c()= 通过 =as.matrix= 转换为矩阵；
+ 直接通过 =matrix= 创建 $n\times 1$ 和 $1\times n$ 的矩阵。

#+begin_src R
  c <- c(1, 2, 3, 4)
  class(c)
#+end_src

#+RESULTS[1d8d10865421d018c0a0fa7429a60795141421bb]:
: [1] "numeric"

可见 =c(1, 2, 3)= 不是矩阵类型。
利用 =as.matrix= 将其转为列向量：

#+begin_src R
  c <- as.matrix(c)
  c
  class(c)
#+end_src

#+RESULTS[259e4128d4a80bad5c06dae0204e92404305e7a5]:
: [,1]
: [1,]    1
: [2,]    2
: [3,]    3
: [4,]    4
: [1] "matrix" "array"

也可以直接用 =matrix= 直接定义列向量：

#+begin_src R
  c1 <- matrix(c(1,2,3,4), 4, 1)
  identical(c, c1) # 判断 c 和 c1 是否相等
#+end_src

#+RESULTS[1bb64a1081c8bda33db59fab144a2afa74d36a48]:
: [1] TRUE

** 改变矩阵

假设 $5\times 3$ 矩阵
$A=\left[\begin{array}{cc}
1 & -6 & 11\\
2 & -7 & 12\\
3 & -8 & 13\\
4 & -9 & 14\\
5 & -10 & 15
\end{array}\right]$

#+begin_src R
  A <- matrix(c(1, 2, 3, 4, 5, -6, -7, -8, -9, -10, 11, 12, 13, 14, 15), 5, 3)
  A
#+end_src

#+RESULTS[9725140a89614f4baaaab1ae48e6495034ed16ae]:
: [,1] [,2] [,3]
: [1,]    1   -6   11
: [2,]    2   -7   12
: [3,]    3   -8   13
: [4,]    4   -9   14
: [5,]    5  -10   15

把 $A$ 的第 2 行替换为 21, 22, 23 ，得到矩
$B=\left[\begin{array}{cc}
1 & -6 & 11\\
21 & 22 & 23\\
3 & -8 & 13\\
4 & -9 & 14\\
5 & -10 & 15
\end{array}\right]$ ：

#+begin_src R
  B <- A
  B[2,] <- c(21, 22, 23)
  B
#+end_src

#+RESULTS[030d1445fc517d14c0dcd90053bf6d723a043339]:
: [,1] [,2] [,3]
: [1,]    1   -6   11
: [2,]   21   22   23
: [3,]    3   -8   13
: [4,]    4   -9   14
: [5,]    5  -10   15

=rbind()= 将两个列数一样的矩阵上、下拼接起来：

#+begin_src R
  rbind(A,B)
#+end_src

#+RESULTS:
#+begin_example
      [,1] [,2] [,3]
 [1,]    1   -6   11
 [2,]    2   -7   12
 [3,]    3   -8   13
 [4,]    4   -9   14
 [5,]    5  -10   15
 [6,]    1   -6   11
 [7,]   21   22   23
 [8,]    3   -8   13
 [9,]    4   -9   14
[10,]    5  -10   15
#+end_example

=cbind= 将两个行数一样的矩阵左、右拼接起来：

#+begin_src R
  cbind(A,B)
#+end_src

#+RESULTS:
:      [,1] [,2] [,3] [,4] [,5] [,6]
: [1,]    1   -6   11    1   -6   11
: [2,]    2   -7   12   21   22   23
: [3,]    3   -8   13    3   -8   13
: [4,]    4   -9   14    4   -9   14
: [5,]    5  -10   15    5  -10   15

删去 $A$ 的第 2 行

#+begin_src R
  A[-2,]
#+end_src

#+RESULTS:
:      [,1] [,2] [,3]
: [1,]    1   -6   11
: [2,]    3   -8   13
: [3,]    4   -9   14
: [4,]    5  -10   15

删去 $A$ 第 2，4 行：

#+begin_src R
  A[-c(2, 4),]
#+end_src

#+RESULTS:
:      [,1] [,2] [,3]
: [1,]    1   -6   11
: [2,]    3   -8   13
: [3,]    5  -10   15

删去 $A$ 第 2-4 行：

#+begin_src R
  A[-c(2:4),]
#+end_src

#+RESULTS:
:      [,1] [,2] [,3]
: [1,]    1   -6   11
: [2,]    5  -10   15

** 矩阵运算

创建矩阵
$A=\left[\begin{array}{cc}
1 & 4\\
2 & 5\\
3 & 6
\end{array}\right]$
，
$B=\left[\begin{array}{cc}
0 & -1\\
2 & 1\\
1 & 3
\end{array}\right]$
以及
$C=\left[\begin{array}{cc}
3 & -2\\
2 & 1
\end{array}\right]$

#+begin_src R
  A <- matrix(c(1, 2, 3, 4, 5, 6), 3, 2)
  B <- matrix(c(0, 2, 1, -1, 1, 3), 3, 2)
  C <- matrix(c(3, 2, -2, 1), 2, 2)
#+end_src

#+RESULTS[d2c2fef2d6fa4273f1454d945e8971ac329d750a]:

转置 =t()= 将矩阵的行和列互换：

#+begin_src R
  t(A)
#+end_src

#+RESULTS[78e7bb20cae0be00971f9a95adcae2551108bfce]:
:      [,1] [,2] [,3]
: [1,]    1    2    3
: [2,]    4    5    6

矩阵的加法：

#+begin_src R
  A + B
#+end_src

#+RESULTS[5b40e239c961a1cb0dd212756d1c07e2004cf443]:
:      [,1] [,2]
: [1,]    1    3
: [2,]    4    6
: [3,]    4    9

减法：

#+begin_src R
  A - B
#+end_src

#+RESULTS[493027cfa5e52d180d4783b4b245293e1a35e233]:
:      [,1] [,2]
: [1,]    1    5
: [2,]    0    4
: [3,]    2    3

数乘：

#+begin_src R
  2 * A
#+end_src

#+RESULTS[1c9aa70157eb0e012511af93d407513931d5b76a]:
:      [,1] [,2]
: [1,]    2    8
: [2,]    4   10
: [3,]    6   12

矩阵乘法用 =%*%= ：

#+begin_src R
  A %*% C
#+end_src

#+RESULTS[3ca8c571b400f2bfe3ed2a7cb4f930710b8632d3]:
:      [,1] [,2]
: [1,]   11    2
: [2,]   16    1
: [3,]   21    0

要注意的是， =A * B= 表示同阶的两个矩阵 *逐元素相乘* ：

#+begin_src R
  A * B
#+end_src

#+RESULTS[71606536a02a5302d2dc4606949c83473ea2442e]:
:      [,1] [,2]
: [1,]    0   -4
: [2,]    4    5
: [3,]    3   18

求向量的长度：

#+begin_src R
  a <- as.matrix(c(4, 1, 1, 1, 3, 6))
  sqrt(t(a) %*% a)
#+end_src

#+RESULTS[0b35e597ab65f53b5cebf039844ae3da586a9ebc]:
: [,1]
: [1,]    8

** 特殊矩阵

对角矩阵用 =diag= 创建：

#+begin_src R
  diag(c(1, 2, 3, 4), 4, 4)
#+end_src

#+RESULTS[a7688f77880e5f2cf6892ba389301f030ac58399]:
:      [,1] [,2] [,3] [,4]
: [1,]    1    0    0    0
: [2,]    0    2    0    0
: [3,]    0    0    3    0
: [4,]    0    0    0    4

单位矩阵：

#+begin_src R
  diag(1, 4, 4)
#+end_src

#+RESULTS[55e3573a9a1da065eba0868f3d7413e6164fc8b5]:
:      [,1] [,2] [,3] [,4]
: [1,]    1    0    0    0
: [2,]    0    1    0    0
: [3,]    0    0    1    0
: [4,]    0    0    0    1

** 矩阵求逆

设
$A=\left[\begin{array}{cc}
0 & 2 & 9\\
9 & 2 & 4\\
3 & 1 & 4
\end{array}\right]$。

#+begin_src R
  A <- matrix(c(0, 9, 3, 2, 2, 1, 9, 4, 4), nrow = 3, ncol = 3)
#+end_src

#+RESULTS[6c448977285f7ab4abb9b2a924adccacc21aff44]:

=solve(A)= 可以求出方阵 $A$ 的逆矩阵 =A_inv= ：

#+begin_src R
  A_inv <- solve(A)
  A_inv
#+end_src

#+RESULTS[e0d704be107e2d9c8d9fc7f276569f535c5786ba]:
: [,1]        [,2]       [,3]
: [1,] -0.1904762 -0.04761905  0.4761905
: [2,]  1.1428571  1.28571429 -3.8571429
: [3,] -0.1428571 -0.28571429  0.8571429

验证 =A= 与 =A_inv= 的乘积是否等于单位矩阵：

#+begin_src R
  D <- A %*% A_inv
  D
#+end_src

#+RESULTS[7ecdd150a080edb2da2e235e6c73c2f37c929f72]:
: [,1] [,2]          [,3]
: [1,] 1.000000e+00    0  0.000000e+00
: [2,] 1.110223e-16    1 -4.440892e-16
: [3,] 0.000000e+00    0  1.000000e+00

因为计算过程无可避免产生误差，两者的乘积 =D= 只是非常接近单位矩阵。
使用 =zapsmall(D)= 对 =D= 进行四舍五入后， 的确等于单位矩阵：

#+begin_src R
  zapsmall(D)
#+end_src

#+RESULTS[567ef283876425065b3cd674f1bb1939a7c7f0bd]:
:      [,1] [,2] [,3]
: [1,]    1    0    0
: [2,]    0    1    0
: [3,]    0    0    1

如果希望逆矩阵中的元素表示为分式（而不是小数），可以采用 =MASS= package  中的 =fractions= 函数：

#+begin_src R
  fractions(A_inv)
#+end_src

#+RESULTS[879160552b24625b39912c8b9346cead1e7d1c7f]:
:      [,1]  [,2]  [,3] 
: [1,] -4/21 -1/21 10/21
: [2,]   8/7   9/7 -27/7
: [3,]  -1/7  -2/7   6/7

=MASS= 是 =R= 的内置宏包，不需要安装，但需要通过 =library(MASS)= 加载。

** 特征向量和特征值

设矩阵
$A=\left[\begin{array}{cc}
1 & -1 & 1\\
2 & 4 & -2\\
-3 & -3 & 5
\end{array}\right]$。

#+begin_src R
  A <- matrix(c(1, 2, -3, -1, 4, -3, 1, -2, 5), 3, 3)
#+end_src

#+RESULTS[87666ccc04da39745832fcebcbaa5da2b0b7f27d]:

=eigen(A)= 可以求出 $A$ 的特征值和特征向量：

#+begin_src R
  E <- eigen(A)
  E
#+end_src

#+RESULTS[db67e4d73d217f53f5ac7d11e60f23395d5a5415]:
: eigen() decomposition
: $values
: [1] 6 2 2
: 
: $vectors
:            [,1]       [,2]       [,3]
: [1,] -0.2672612 -0.5055851 -0.8111071
: [2,]  0.5345225  0.8080292  0.3244428
: [3,] -0.8017837  0.3024441 -0.4866643

其中 $A$ 的特征值为：

#+begin_src R
  E$values
#+end_src

#+RESULTS[40a05a92fc40f1724de1c9f9169ac15f08d16032]:
: [1] 6 2 2

相应的特征向量依次为：

#+begin_src R
  E$vectors
#+end_src

#+RESULTS[d694d14dde008e75cee714929759b0febc8f2ad8]:
:            [,1]       [,2]       [,3]
: [1,] -0.2672612 -0.5055851 -0.8111071
: [2,]  0.5345225  0.8080292  0.3244428
: [3,] -0.8017837  0.3024441 -0.4866643

这里的特征向量已经进行了单位化。

* 阶梯形矩阵与线性方程组

=matlib= 是专门为了教学和线性代数可视化设计的包，在处理矩阵时非常实用，比如：
+ 求分数形式的逆矩阵 / 高斯消元： =Inverse(A)=  或 =gaussianElimination(A)=
+ 求解线性方程组 $Ax = b$： =Solve(A, b)= 
+ 通过 =showEqn(A, b)= 打印漂亮的方程组
+ 向量与矩阵变换可视化： =plotEqn()= ， =vector3d()= 等

=matlib= 不是 =R= 语言的内置包，而是一个第三方的扩展包，需要先 =install.packages("matlib")= 安装，再 =library(matlib)= 加载。

** 阶梯形矩阵

任意一个矩阵通过行变换，可以化为行阶梯形（Echelon Form）或简化行阶梯形（Reduced Row Echelon Form, RREF）。
默认情况下， =echelon()= 会直接计算 RREF。

设
$A=\left[\begin{array}{ccccc}
1 & 1 & -1 & -1 & 1\\
3 & 5 & -6 & -1 & 1\\
-2 & 2 & -4 & 6 & -6
\end{array}\right]$

#+begin_src R
  A <- matrix(c(1, 3, -2, 1, 5, 2, -1, -6, -4, -1, -1, 6, 1, 1, -6), 3, 5)
#+end_src

#+RESULTS:

=echelon(A)= 得到 $A$ 的简化行阶梯形：

#+begin_src R
  echelon(A)
#+end_src

#+RESULTS:
:      [,1] [,2] [,3] [,4] [,5]
: [1,]    1    0  0.5   -2    2
: [2,]    0    1 -1.5    1   -1
: [3,]    0    0  0.0    0    0

如果增加参数 =fractions = TRUE= ，那么结果输出为精确的最简分数：

#+begin_src R
  echelon(A,  fractions = TRUE)
#+end_src

#+RESULTS:
:      [,1] [,2] [,3] [,4] [,5]
: [1,]    1    0  1/2   -2    2
: [2,]    0    1 -3/2    1   -1
: [3,]    0    0    0    0    0

增加参数 =verbose = TRUE= 可以显示行变换的具体步骤：

#+begin_src R :warning no
  echelon(A, verbose = TRUE, fractions = TRUE)
#+end_src

#+RESULTS:
#+begin_example

Initial matrix:
     [,1] [,2] [,3] [,4] [,5]
[1,]  1    1   -1   -1    1  
[2,]  3    5   -6   -1    1  
[3,] -2    2   -4    6   -6  

row: 1 

 exchange rows 1 and 2 
     [,1] [,2] [,3] [,4] [,5]
[1,]  3    5   -6   -1    1  
[2,]  1    1   -1   -1    1  
[3,] -2    2   -4    6   -6  

 multiply row 1 by 1/3 
     [,1] [,2] [,3] [,4] [,5]
[1,]    1  5/3   -2 -1/3  1/3
[2,]    1    1   -1   -1    1
[3,]   -2    2   -4    6   -6

 subtract row 1 from row 2 
     [,1] [,2] [,3] [,4] [,5]
[1,]    1  5/3   -2 -1/3  1/3
[2,]    0 -2/3    1 -2/3  2/3
[3,]   -2    2   -4    6   -6

 multiply row 1 by 2 and add to row 3 
     [,1]  [,2]  [,3]  [,4]  [,5] 
[1,]     1   5/3    -2  -1/3   1/3
[2,]     0  -2/3     1  -2/3   2/3
[3,]     0  16/3    -8  16/3 -16/3

row: 2 

 exchange rows 2 and 3 
     [,1]  [,2]  [,3]  [,4]  [,5] 
[1,]     1   5/3    -2  -1/3   1/3
[2,]     0  16/3    -8  16/3 -16/3
[3,]     0  -2/3     1  -2/3   2/3

 multiply row 2 by 3/16 
     [,1] [,2] [,3] [,4] [,5]
[1,]    1  5/3   -2 -1/3  1/3
[2,]    0    1 -3/2    1   -1
[3,]    0 -2/3    1 -2/3  2/3

 multiply row 2 by 5/3 and subtract from row 1 
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0  1/2   -2    2
[2,]    0    1 -3/2    1   -1
[3,]    0 -2/3    1 -2/3  2/3

 multiply row 2 by 2/3 and add to row 3 
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0  1/2   -2    2
[2,]    0    1 -3/2    1   -1
[3,]    0    0    0    0    0
#+end_example

** 零空间、行空间、列空间

假设矩阵$A=\left[\begin{array}{ccccc}
1 & 1 & -1 & -1\\
3 & 5 & -6 & -1\\
-2 & 2 & -4 & 6
\end{array}\right]$。
那么 $A$ 的 *零空间* $\ker A = \{x : Ax=0\}$。
$A$ 的行空间与零空间 $\ker A$ 正好构成 $\mathbb{R}^{4}$ 的正交补空间。

=MASS= package 中的函数 =NULL()= 可以用来计算 $\ker A$ 的一组 *单位正交基* ：

#+begin_src R
  A <- matrix(c(1, 3, -2, 1, 5, 2, -1, -6, -4, -1, -1, 6), 3, 4)
  B <- Null(t(A))
  B
#+end_src

#+RESULTS:
: [,1]        [,2]
: [1,] 0.1745277  0.82547228
: [2,] 0.7091205 -0.37578713
: [3,] 0.6371075  0.02955921
: [4,] 0.2465407  0.42012594

要注意代码是 =Null(t(A))= ，不能省略转置 =t(A)= 。

另一方面，计算 $A$ 的简化阶梯形：

#+begin_src R
  C <- echelon(A)
  C
#+end_src

#+RESULTS:
: [,1] [,2] [,3] [,4]
: [1,]    1    0  0.5   -2
: [2,]    0    1 -1.5    1
: [3,]    0    0  0.0    0

由此可知：
+ $A$ 的列空间的一组基是 =C[1,]= 和 =C[2,]= 。
+ $A$ 的行空间的一组基是 =A[,1]= 和 =A[,2]= 。（注意，因为行秩等于列秩，行空间和列空间的维数一定相等。）

** 方程组

考虑线性方程组
$$\left\{ \begin{array}{l}
x_{1}+x_{2}-x_{3}-x_{4}=1\\
3x_{1}+5x_{2}-6x_{3}-x_{4}=1\\
-2x_{1}+2x_{2}-4x_{3}+6x_{4}=-6
\end{array}\right.$$

系数矩阵 $A=\left[\begin{array}{ccccc}
1 & 1 & -1 & -1\\
3 & 5 & -6 & -1\\
-2 & 2 & -4 & 6
\end{array}\right]$，常数项 $b=\left[\begin{array}{c}
1\\
1\\
-6
\end{array}\right]$，所以方程组可以表示为 $Ax=b$ 。

#+begin_src R
  A <- matrix(c(1, 3, -2, 1, 5, 2, -1, -6, -4, -1, -1, 6), 3, 4)
  b <- matrix(c(1, 1, -6), 3, 1)
#+end_src

#+RESULTS:

=showEqn(A, b)= 是 =matlib= 包提供的格式化显示函数。
它不会进行数值计算，主要作用是将矩阵 $A$ 和向量 $b$ 还原并打印为易读的代数方程组格式。

#+begin_src R
  showEqn(A, b)
#+end_src

#+RESULTS:
:  1*x1 + 1*x2 - 1*x3 - 1*x4  =   1 
:  3*x1 + 5*x2 - 6*x3 - 1*x4  =   1 
: -2*x1 + 2*x2 - 4*x3 + 6*x4  =  -6

=showEqn()= 中可以
+ 增加参数 =fractions = TRUE= 将方程组的系数显示为分数形式；
+ 增加参数 =latex = TRUE= 输出 LaTeX 排版源码。

=matlib= 包中的 =Solve()= （注意首字母大写）是 =R= 内置函数 =solve()= 的一个扩展增强版，专门为教学和符号化推导设计。

#+begin_src R
  Solve(A, b)
#+end_src

#+RESULTS:
: x1   + 0.5*x3 - 2*x4  =   2 
:   x2 - 1.5*x3   + x4  =  -1 
:                    0  =   0

可以加参数 =fractions = TRUE= 把系数写成分数：

#+begin_src R
  Solve(A, b, fractions = TRUE)
#+end_src

#+RESULTS:
: x1   + 1/2*x3 - 2*x4  =   2 
:   x2 - 3/2*x3   + x4  =  -1 
:                    0  =   0

把方程组 $Ax=b$ 化成了「简化阶梯形」。
由此可以知道方程组的通解是
$$\left\{ \begin{array}{l}
x_{1}=2-\frac{1}{2}c_{1}+2c_{2}\\
x_{2}=-1+\frac{3}{2}c_{1}-c_{2}\\
x_{3}=c_{1}\\
x_{4}=c_{2}
\end{array}\right.$$

也可以通过把增广矩阵 $(A, b)$ 化为简化阶梯形矩阵来求解线性方程组，此时用 =echelon()= 函数：

#+begin_src R
  fractions(echelon(cbind(A, b)))
#+end_src

#+RESULTS:
:      [,1] [,2] [,3] [,4] [,5]
: [1,]    1    0  1/2   -2    2
: [2,]    0    1 -3/2    1   -1
: [3,]    0    0    0    0    0
