#+TITLE: 巩固服务器安全
#+AUTHOR: zbliang
#+DATE: 2026-07-13
#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: posts
#+HUGO_PAIRED_OUT_DIR: ../static
#+HUGO_TAGS: 服务器
#+HUGO_CATEGORIES: tech
#+HUGO_DRAFT: false

#+STARTUP: show2levels

在本地生成密钥和公钥
#+begin_src bash
  ssh-keygen -t ed25519 -f ~/.ssh/id_aliyun
#+end_src

生成密钥 ~id_aliyun~ 和公钥 ~id_aliyun.pub~ 。

把 *公钥* ，即 ~id_aliyun.pub~ ，上传到服务器
#+begin_src bash
  ssh-copy-id -i ~/.ssh/id_aliyun.pub root@1.2.3.4
#+end_src

检查是否可以通过密钥登陆
#+begin_src bash
  ssh -i ~/.ssh/id_aliyun root@1.2.3.4
#+end_src

为了避免每次登陆要输入这么长的命令，可以在 ~~/.ssh/config~ 末尾增加
#+begin_example
Host alicloud
	HostName 1.2.3.4
	User root
	IdentityFile ~/.ssh/id_aliyun
	IdentitiesOnly yes
#+end_example
保存后要执行 ~chmod 600 ~/.ssh/config~ ，保证新设置生效。

以后执行 ~ssh alicloud~ 就可以登陆服务器了。

确保可通过公钥登陆服务器后，就可以关闭服务器的密码登陆功能。

在服务器里执行 ~sudo nano /etc/ssh/sshd_config~ ，把 ~PasswordAuthentication yes~ 改为 ~PasswordAuthentication no~ 。
也可以把后者直接粘贴到最后，就能覆盖前面的设置。
同时增加 ~PubkeyAuthentication yes~ 。
修改配置后必须重启服务才会生效：
#+begin_src bash
  # Ubuntu/Debian 系统
  sudo systemctl restart sshd
#+end_src

创建普通用户并赋予 sudo 权限

不要长期使用 root 。所以要新建一个新用户，例如 apple ：

#+begin_src bash
  sudo adduser apple
#+end_src

设置密码（可适中复杂度）。
因为已经关闭了服务器密码登录，只允许密钥登录，所以即便 apple 密码设简单一点，不会被外部暴力破解。
apple 用户的密码只有一种场景会用到，就是 ~sudo 命令~ 。
但是也不应该太简单：

1. 防止本地机器被入侵后，攻击者轻松提权。
2. 有些漏洞（权限提升类）可以让攻击者在拿到普通用户后，尝试弱密码爆破 sudo，从而拿到 root。

然后赋予新用户 sudo 权限：

#+begin_src bash
  sudo usermod -aG sudo apple
#+end_src

测试：

#+begin_src bash
    su - apple
    sudo whoami
#+end_src

输出 root 表示成功。

禁用 root 直接登录，改为用普通用户（apple）登录，需要时再 sudo 提权。

首先，必须把 SSH 密钥放在 apple 这个用户的目录里。
这个需要手动操作。
#+begin_src bash
  # 切换到 apple 用户的环境（确保目录归属正确）
  su - apple -c "mkdir -p ~/.ssh && chmod 700 ~/.ssh"

  # 把复制的公钥写入 authorized_keys（替换【你的公钥内容】）
  su - apple -c "echo '【你的公钥内容】' >> ~/.ssh/authorized_keys"

  # 设置正确的权限（必须！）
  su - apple -c "chmod 600 ~/.ssh/authorized_keys"
#+end_src

apple 用户的 ~.ssh~ 目录必须是 700， ~authorized_keys~ 必须是 600，否则 SSH 会拒绝使用公钥。

假设公钥是 ~ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIxxx apple@local~ ，那么
#+begin_src bash
  su - apple -c "echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIxxx apple@local' >> ~/.ssh/authorized_keys"
#+end_src

修改本地的 ~~/.ssh/config~ 文件，把 ~User root~ 改为 ~User apple~ 。
保存后执行 ~chmod 600 ~/.ssh/config~ 。
确保 ~ssh alicloud~ 可以成功登陆上服务器的 apple 用户。

这时可以关闭 root 直接登录了。
在服务器里执行 ~sudo nano /etc/ssh/sshd_config~ ，把 ~PermitRootLogin yes~ 改为 ~PermitRootLogin no~ 。
然后重启 SSH：
#+begin_src bash
  sudo systemctl restart ssh
#+end_src


